name: test
on:
  workflow_dispatch: 
  issues:
    types:
      - edited

jobs:
  getenvs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: env
      - run: gh issue view 1
        env:
          GH_TOKEN: ${{ github.token }}
